# Generated by Django 4.2.4 on 2023-08-21 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MusicPlayer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='audio_link',
            new_name='genres',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(default='D:\\Django_main\\PyMusic\\src\\staticimgs/user_default_img.avif', upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default='D:\\Django_main\\PyMusic\\src\\staticimgs/user_default_img.avif', upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song', models.ManyToManyField(to='MusicPlayer.song')),
            ],
        ),
    ]
