# Generated by Django 4.2.4 on 2023-08-22 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MusicPlayer', '0002_rename_audio_link_song_genres_remove_song_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='listeners',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
