# Generated by Django 4.2.4 on 2023-08-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPlayer', '0003_song_listeners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
