# Generated by Django 4.2.4 on 2023-08-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPlayer', '0005_alter_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(blank=True, default='default name', max_length=200),
        ),
    ]
